// Generated by https://quicktype.io

export interface CommitResponse {
  sha: string;
  node_id: string;
  commit: CommitClass;
  url: string;
  html_url: string;
  comments_url: string;
  author: CommitAuthor;
  committer: CommitAuthor;
  parents: Parent[];
}

export interface CommitAuthor {
  login: Login;
  id: number;
  node_id: NodeID;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: FollowingURL;
  gists_url: GistsURL;
  starred_url: StarredURL;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: EventsURL;
  received_events_url: string;
  type: Type;
  site_admin: boolean;
}

export enum EventsURL {
  HTTPSAPIGithubCOMUsersGetellezEventsPrivacy = 'https://api.github.com/users/getellez/events{/privacy}',
}

export enum FollowingURL {
  HTTPSAPIGithubCOMUsersGetellezFollowingOtherUser = 'https://api.github.com/users/getellez/following{/other_user}',
}

export enum GistsURL {
  HTTPSAPIGithubCOMUsersGetellezGistsGistID = 'https://api.github.com/users/getellez/gists{/gist_id}',
}

export enum Login {
  Getellez = 'getellez',
}

export enum NodeID {
  MDQ6VXNlcjg1OTY4MTE3 = 'MDQ6VXNlcjg1OTY4MTE3',
}

export enum StarredURL {
  HTTPSAPIGithubCOMUsersGetellezStarredOwnerRepo = 'https://api.github.com/users/getellez/starred{/owner}{/repo}',
}

export enum Type {
  User = 'User',
}

export interface CommitClass {
  author: CommitAuthorClass;
  committer: CommitAuthorClass;
  message: string;
  tree: Tree;
  url: string;
  comment_count: number;
  verification: Verification;
}

export interface CommitAuthorClass {
  name: Name;
  email: Email;
  date: string;
}

export enum Email {
  GertellezvGmailCOM = 'gertellezv@gmail.com',
}

export enum Name {
  GermanTellez = 'German Tellez',
}

export interface Tree {
  sha: string;
  url: string;
}

export interface Verification {
  verified: boolean;
  reason: string;
  signature: null;
  payload: null;
}

export interface Parent {
  sha: string;
  url: string;
  html_url: string;
}
